name: Matchbot Main

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install NPM packages
        run: npm install

      - name: Build frontend
        run: npm run prod
  
      - name: Deploy to server
        uses: contention/rsync-deployments@v2.0.0
        with:
          FLAGS: -avzr --delete
          USER: ${{ secrets.DEPLOY_USER }}
          HOST: ${{ secrets.DEPLOY_HOST }}
          LOCALPATH: ./
          REMOTEPATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Run deploy script
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.DEPLOY_USER }}
          host: ${{ secrets.DEPLOY_HOST }}
          script: "cd /var/www/matchbot-livewire && ./deploy.sh"
