name: Matchbot Main

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install NPM packages
        run: npm install

      - name: Build frontend
        run: npm run production

      - name: Deploy to server
        uses: aburnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: src/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Run deploy script
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.DEPLOY_USER }}
          host: ${{ secrets.DEPLOY_HOST }}
          script: "cd /var/www/matchbot-livewire && ./deploy.sh"
